#107 Adicionado Outras no seed Drogas
EscolaDeSaudePublica/registrocovid-api pull request #111
Opened 2020-09-23 20:34 UTC by FelipeSVidal

Incluir opção "Outras" no seeds de drogas.
Essa inclusão deve aparecer no frontend da Categoria de "História pessoal"
Incluir opção "Outras" no modelo de dados (draw.io)

2020-09-23 20:58 UTC, victorMagalhaesPacheco commented
Necessário resolver os testes.
Erro: 

```
1) Tests\Feature\Drogas\CadastroDeDrogaTest::testCriandoDrogaComSucesso
Expected status code 201 but received 500.
Failed asserting that 201 is identical to 500.
```

2020-09-28 13:35 UTC, chicaothiago requested changes
Remover um var_dump n omeio do código.
E só uma dúvida que se poder ser respondida, agradeceria :D

2020-09-28 13:35 UTC, chicaothiago commented on tests/Feature/Drogas/CadastroDeDrogaTest.php
> +        var_dump($response);
remover VAR_DUMP

2020-09-28 13:35 UTC, chicaothiago commented on tests/Feature/Drogas/ListaDeDrogasCadastradasTest.php
> +        $response->assertJsonCount(5);
Este teste não fica amarrado? Não tem uma chance muito grnade de falhar por uma simples alteração no banco? À criação do seed? Não existe a possibildiade de cadastro de uma nova droga pelo sitema?

2020-09-28 14:15 UTC, FelipeSVidal commented on tests/Feature/Drogas/ListaDeDrogasCadastradasTest.php
> +        $response->assertJsonCount(5);
Sim fica, dentro do sistema não tem a opção de criar uma droga. Pelo pouco que vi existe uma rota, mas não é usada!

2020-09-29 12:58 UTC, chicaothiago approved these changes

2020-09-29 17:09 UTC, merged