Ajuste seeds Tipo de suporte
EscolaDeSaudePublica/registrocovid-api pull request #115
Opened 2020-09-25 20:37 UTC by FelipeSVidal

- [x] Ajuste no seeds de tipo de suporte - deve refletir o modelo de dados ( a ordem é importante, e deve ser a ordem que está no modelo)

  - Catéter nasal de baixo fluxo - era Cateter de o2
  - Catéter nasal de alto fluxo - era Cânula nalsal de alto fluxo
  - **Máscara de Venturi - foi adicionado**
  - Máscara com reservatório - era  Máscara de reservatório
  - **Ventilação mecânica não Invasiva (VNI) - foi adicionado**
  - Ventilação mecânica invasiva  - era Ventilação invasiva
  - Intubação Orotraqueal - era Tubo
  - Traqueostomia (fica igual)
  - **Oxigenação por membrana extracorpórea (ECMO) - foi adicionado**
  - Pronação (fica igual)
  - Inclusão em desmame da ventilação mecânica - era Inclusão no desmame da VM

- [x] Adicionar mais um campo na tabela de pacientes, com o nome: chegou_traqueostomizado (já foi incluído no modelo)

- [x] Adicionar os campos abaixo na tabela de suporte_respiratório:

  - Alterar parametro para "fluxo_o2"
  - Acrescentar concentracao_o2 (float)
  - Acrescentar fluxo_sangue (float)
  - Acrescentar fluxo_gasoso (float)
  - Acrescentar fio2 (float)

2020-09-28 14:26 UTC, chicaothiago requested changes
Consideraria trocar o nome da migration para a ação que reflete a migration, para facilitar o entendimento da execução das alterações no banco de dados.

2020-09-28 14:26 UTC, chicaothiago commented on database/migrations/2020_09_25_194651_update_pacientes.php
> +class UpdatePacientes extends Migration
Eu consideraria o nome da migration ser a ação que ela irá realizar, para ser mais fácil de se entender o que está sendo executado na migration.

2020-09-28 17:31 UTC, FelipeSVidal commented on database/migrations/2020_09_25_194651_update_pacientes.php
> +class UpdatePacientes extends Migration
Creio que assim dê para entender!

2020-09-29 13:00 UTC, chicaothiago approved these changes

2020-09-29 17:09 UTC, merged