Feature/delete dummy actions
EscolaDeSaudePublica/registrocovid-api pull request #155
Opened 2020-10-22 20:44 UTC by FelipeSVidal

---
Responsáveis: @FelipeSVidal 
Linked Issue: Feature #132 
---

# Descrição

Endpoint que apague todos os dados que o usuário teste criou.

# Passos a passo para teste

Rota: api/dummy

# Observações

- Por hora estou utilizando o id 1, mas ainda será indicado pela Camila qual o ID do usuário.

2020-10-23 17:04 UTC, chicaothiago requested changes
Eu não recomendo criar uma rota para esta alteração de remoção de dados.
Como é algo que teoricamente não vai ser feito constantemente. É bom que seja um comando do laravel que rode diretamente no servidor.

2020-10-23 17:04 UTC, chicaothiago commented on app/Models/TiposSuportesRespiratoriosPaciente.php
> +    public function tipoSuporte()
É aconselhável o nome do método ser o nome da classe referenciada, para facilitar o reconhecimento da referência no banco de dados.

2020-10-23 20:25 UTC, FelipeSVidal commented on app/Models/Historico.php
> +    }
Antes de deletar a entrada em Histórico precisa ser deletado onde ele tem referências, ver diagrama, sem este método dá erro de chave estrangeira nas tabelas subsequentes.

2020-10-23 20:27 UTC, FelipeSVidal commented on app/Models/TiposSuportesRespiratoriosPaciente.php
> +    // protected $table = 'tipos_suportes_respiratorios_pacientes';
Quando estava com o nome da tabela ele apontava para uma tabela diferente, era: pacientes_tipos_..._pacientes!

2020-10-23 20:36 UTC, FelipeSVidal commented on app/Models/TiposSuportesRespiratoriosPaciente.php
> +    ];
Pelo que vi sobre, fillable são as colunas que permitem serem inseridas em massa. No caso posso entrar com uma lista de paciente_id e uma lista de tipo_suporte na inserção.

2020-10-26 16:51 UTC, chicaothiago commented on app/Models/TiposSuportesRespiratoriosPaciente.php
> +    // protected $table = 'tipos_suportes_respiratorios_pacientes';
Muito esquisito até, tu definir o nome da tabela e ele chamar uma table que não fazia sentido hahahahaha. Beleza, se assim  é que funciona, ta joia.

2020-10-26 16:53 UTC, chicaothiago commented on app/Models/TiposSuportesRespiratoriosPaciente.php
> +    ];
Entendi. Eu sempre colocava todos porque por mim fazia sentido para usar função fill(), que usei muito em um outro projeto, ele usa no construtor, se não me engano.
Ta joia

2020-10-26 17:31 UTC, FelipeSVidal commented on app/Models/Paciente.php
>              foreach ($postData->tipos_suporte_respiratorio as $suporte_id) {
Não sei exatamente qual o funcionamento desse método. Então o if é dispensável dado que tem um isset antes?

2020-10-26 17:51 UTC, chicaothiago approved these changes

2020-10-26 17:52 UTC, FelipeSVidal commented
`Então esse método puxa a remoção em cascata do banco de dados?`
Sim!

2020-10-27 19:13 UTC, merged