Feature/170 alterar campos historia pessoal
EscolaDeSaudePublica/registrocovid-api pull request #180
Opened 2020-12-02 20:13 UTC by FelipeSVidal

---
Responsáveis: @FelipeSVidal 
Linked Issue: Fix #170 
---

# Descrição

Adicionado situação Tabagismo e Etilismo para historia pessoal

# Passos a passo para teste

Adicionar um novo histórico, informando os campos situacao_tabagismo_id e situacao_etilismo_id!

2020-12-03 20:22 UTC, chicaothiago requested changes
Atenção primordial com a mudança do seed, pois o fluxo agora é diferente.

2020-12-03 21:19 UTC, FelipeSVidal commented on app/Http/Requests/HistoricoRequest.php
> +            'situacao_etilismo_id' => 'int|exists:situacao_etilismo,id',
Sim, já está em dev essa atividade no front. Só vamos fazer o merge quando ambas estiverem feitas e testadas!

2020-12-09 12:45 UTC, chicaothiago requested changes

2020-12-09 12:45 UTC, chicaothiago commented on app/Http/Controllers/Api/Paciente/Historico/HistoricoController.php
> +                    204
Esse status é comumente usado em requisições PUT, onde temos um sucesso mas nenhum conteúdo foi encontrado. 
Quando usamos na API o comum é usar 404 mesmo, que significa que não obteve o resultado esperado. 
Inclusive, você retorna um ErrorMessage no json.
Então, o status deve continuar como 404 mesmo.

2020-12-09 18:16 UTC, FelipeSVidal commented on app/Http/Controllers/Api/Paciente/Historico/HistoricoController.php
> +                    204
Foi um pedido do front, devo botar 404 ou deixo 204 nesse caso?

2020-12-11 13:04 UTC, chicaothiago commented on app/Http/Controllers/Api/Paciente/Historico/HistoricoController.php
> +                    204
Foi removido o 404 e posto 204.
É para manter o 404.

2020-12-15 15:36 UTC, chicaothiago approved these changes

2020-12-15 15:38 UTC, chicaothiago requested changes
Precisa arrumar os testes

2020-12-17 19:31 UTC, chicaothiago approved these changes

2020-12-18 17:59 UTC, merged